services:
  db:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      timeout: 2s
      start_period: 10s
    volumes:
      - ./data/db:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net

  rabbitmq:
    image: rabbitmq:4.3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_NODENAME: rabbit@rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      retries: 10
      timeout: 2s
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbitmq-net

  api:
    image: node:26-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "3000:3000"
    networks:
      - db-net
      - rabbitmq-net
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  server-manager:
    image: golang:1.26-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - db-net
      - rabbitmq-net
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  game-server:
    build:
      context: ./game-server
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - rabbitmq-net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  db-net:
    driver: bridge
    internal: true
  rabbitmq-net:
    driver: bridge
    internal: true


