services:
  db:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net

  api:
    image: node:26-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "3000:3000"
    networks:
      - db-net
      - rabbitmq-net
    depends_on:
      - db
      - rabbitmq

  server-manager:
    image: golang:1.26-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - db-net
      - rabbitmq-net
    depends_on:
      - db
      - rabbitmq

  game-server:
    build:
      context: ./server
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - rabbitmq-net
    depends_on:
      - server-manager

  rabbitmq:
    image: rabbitmq:4.3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_NODENAME: rabbit@rabbitmq
    ports:
      - "127.0.0.1:15672:15672"
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbitmq-net

networks:
  db-net:
    driver: bridge
    internal: true
  rabbitmq-net:
    driver: bridge
    internal: true


