// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cenkalti/backoff/v6 (interfaces: BackOff)
//
// Generated by this command:
//
//	mockgen -destination=./../internal/mocks/backoff.go -package=mocks github.com/cenkalti/backoff/v6 BackOff
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBackOff is a mock of BackOff interface.
type MockBackOff struct {
	ctrl     *gomock.Controller
	recorder *MockBackOffMockRecorder
	isgomock struct{}
}

// MockBackOffMockRecorder is the mock recorder for MockBackOff.
type MockBackOffMockRecorder struct {
	mock *MockBackOff
}

// NewMockBackOff creates a new mock instance.
func NewMockBackOff(ctrl *gomock.Controller) *MockBackOff {
	mock := &MockBackOff{ctrl: ctrl}
	mock.recorder = &MockBackOffMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackOff) EXPECT() *MockBackOffMockRecorder {
	return m.recorder
}

// NextBackOff mocks base method.
func (m *MockBackOff) NextBackOff() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextBackOff")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// NextBackOff indicates an expected call of NextBackOff.
func (mr *MockBackOffMockRecorder) NextBackOff() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextBackOff", reflect.TypeOf((*MockBackOff)(nil).NextBackOff))
}

// Reset mocks base method.
func (m *MockBackOff) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockBackOffMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockBackOff)(nil).Reset))
}
