// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./mocks/interface.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	internal "server-manager/internal"

	gomock "go.uber.org/mock/gomock"
)

// MockDockerConnection is a mock of DockerConnection interface.
type MockDockerConnection struct {
	ctrl     *gomock.Controller
	recorder *MockDockerConnectionMockRecorder
	isgomock struct{}
}

// MockDockerConnectionMockRecorder is the mock recorder for MockDockerConnection.
type MockDockerConnectionMockRecorder struct {
	mock *MockDockerConnection
}

// NewMockDockerConnection creates a new mock instance.
func NewMockDockerConnection(ctrl *gomock.Controller) *MockDockerConnection {
	mock := &MockDockerConnection{ctrl: ctrl}
	mock.recorder = &MockDockerConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerConnection) EXPECT() *MockDockerConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDockerConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDockerConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDockerConnection)(nil).Close))
}

// GetGamePort mocks base method.
func (m *MockDockerConnection) GetGamePort(ctx context.Context, containerID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGamePort", ctx, containerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGamePort indicates an expected call of GetGamePort.
func (mr *MockDockerConnectionMockRecorder) GetGamePort(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGamePort", reflect.TypeOf((*MockDockerConnection)(nil).GetGamePort), ctx, containerID)
}

// KillContainer mocks base method.
func (m *MockDockerConnection) KillContainer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KillContainer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// KillContainer indicates an expected call of KillContainer.
func (mr *MockDockerConnectionMockRecorder) KillContainer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillContainer", reflect.TypeOf((*MockDockerConnection)(nil).KillContainer), ctx, id)
}

// Open mocks base method.
func (m *MockDockerConnection) Open(config *internal.EnvConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockDockerConnectionMockRecorder) Open(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockDockerConnection)(nil).Open), config)
}

// RestartContainer mocks base method.
func (m *MockDockerConnection) RestartContainer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartContainer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestartContainer indicates an expected call of RestartContainer.
func (mr *MockDockerConnectionMockRecorder) RestartContainer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartContainer", reflect.TypeOf((*MockDockerConnection)(nil).RestartContainer), ctx, id)
}

// SpawnContainer mocks base method.
func (m *MockDockerConnection) SpawnContainer(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnContainer", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpawnContainer indicates an expected call of SpawnContainer.
func (mr *MockDockerConnectionMockRecorder) SpawnContainer(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnContainer", reflect.TypeOf((*MockDockerConnection)(nil).SpawnContainer), ctx)
}

// MockBrokerConnection is a mock of BrokerConnection interface.
type MockBrokerConnection struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerConnectionMockRecorder
	isgomock struct{}
}

// MockBrokerConnectionMockRecorder is the mock recorder for MockBrokerConnection.
type MockBrokerConnectionMockRecorder struct {
	mock *MockBrokerConnection
}

// NewMockBrokerConnection creates a new mock instance.
func NewMockBrokerConnection(ctrl *gomock.Controller) *MockBrokerConnection {
	mock := &MockBrokerConnection{ctrl: ctrl}
	mock.recorder = &MockBrokerConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerConnection) EXPECT() *MockBrokerConnectionMockRecorder {
	return m.recorder
}

// AssignJob mocks base method.
func (m *MockBrokerConnection) AssignJob(ctx context.Context, workerID string, config internal.MatchConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignJob", ctx, workerID, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignJob indicates an expected call of AssignJob.
func (mr *MockBrokerConnectionMockRecorder) AssignJob(ctx, workerID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignJob", reflect.TypeOf((*MockBrokerConnection)(nil).AssignJob), ctx, workerID, config)
}

// Close mocks base method.
func (m *MockBrokerConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrokerConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrokerConnection)(nil).Close))
}

// GetResult mocks base method.
func (m *MockBrokerConnection) GetResult(ctx context.Context) (internal.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult", ctx)
	ret0, _ := ret[0].(internal.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResult indicates an expected call of GetResult.
func (mr *MockBrokerConnectionMockRecorder) GetResult(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockBrokerConnection)(nil).GetResult), ctx)
}

// GetWorkersPong mocks base method.
func (m *MockBrokerConnection) GetWorkersPong(ctx context.Context) (internal.Responders, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkersPong", ctx)
	ret0, _ := ret[0].(internal.Responders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkersPong indicates an expected call of GetWorkersPong.
func (mr *MockBrokerConnectionMockRecorder) GetWorkersPong(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkersPong", reflect.TypeOf((*MockBrokerConnection)(nil).GetWorkersPong), ctx)
}

// Open mocks base method.
func (m *MockBrokerConnection) Open(ctx context.Context, config *internal.EnvConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockBrokerConnectionMockRecorder) Open(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockBrokerConnection)(nil).Open), ctx, config)
}

// MockWorkerManager is a mock of WorkerManager interface.
type MockWorkerManager struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerManagerMockRecorder
	isgomock struct{}
}

// MockWorkerManagerMockRecorder is the mock recorder for MockWorkerManager.
type MockWorkerManagerMockRecorder struct {
	mock *MockWorkerManager
}

// NewMockWorkerManager creates a new mock instance.
func NewMockWorkerManager(ctrl *gomock.Controller) *MockWorkerManager {
	mock := &MockWorkerManager{ctrl: ctrl}
	mock.recorder = &MockWorkerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerManager) EXPECT() *MockWorkerManagerMockRecorder {
	return m.recorder
}

// AssignMatch mocks base method.
func (m *MockWorkerManager) AssignMatch(ctx context.Context, config internal.MatchConfig) (internal.ServerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignMatch", ctx, config)
	ret0, _ := ret[0].(internal.ServerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignMatch indicates an expected call of AssignMatch.
func (mr *MockWorkerManagerMockRecorder) AssignMatch(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignMatch", reflect.TypeOf((*MockWorkerManager)(nil).AssignMatch), ctx, config)
}

// Shutdown mocks base method.
func (m *MockWorkerManager) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockWorkerManagerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockWorkerManager)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockWorkerManager) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockWorkerManagerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWorkerManager)(nil).Start), ctx)
}

// WaitForFreeWorker mocks base method.
func (m *MockWorkerManager) WaitForFreeWorker(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WaitForFreeWorker", ctx)
}

// WaitForFreeWorker indicates an expected call of WaitForFreeWorker.
func (mr *MockWorkerManagerMockRecorder) WaitForFreeWorker(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForFreeWorker", reflect.TypeOf((*MockWorkerManager)(nil).WaitForFreeWorker), ctx)
}

// MockDatabaseConnection is a mock of DatabaseConnection interface.
type MockDatabaseConnection struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseConnectionMockRecorder
	isgomock struct{}
}

// MockDatabaseConnectionMockRecorder is the mock recorder for MockDatabaseConnection.
type MockDatabaseConnectionMockRecorder struct {
	mock *MockDatabaseConnection
}

// NewMockDatabaseConnection creates a new mock instance.
func NewMockDatabaseConnection(ctrl *gomock.Controller) *MockDatabaseConnection {
	mock := &MockDatabaseConnection{ctrl: ctrl}
	mock.recorder = &MockDatabaseConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseConnection) EXPECT() *MockDatabaseConnectionMockRecorder {
	return m.recorder
}

// AddMatch mocks base method.
func (m *MockDatabaseConnection) AddMatch(ctx context.Context, users []internal.User, serverInfo internal.ServerInfo, matchId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMatch", ctx, users, serverInfo, matchId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMatch indicates an expected call of AddMatch.
func (mr *MockDatabaseConnectionMockRecorder) AddMatch(ctx, users, serverInfo, matchId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMatch", reflect.TypeOf((*MockDatabaseConnection)(nil).AddMatch), ctx, users, serverInfo, matchId)
}

// Close mocks base method.
func (m *MockDatabaseConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabaseConnection)(nil).Close))
}

// GetList mocks base method.
func (m *MockDatabaseConnection) GetList(ctx context.Context) ([]internal.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx)
	ret0, _ := ret[0].([]internal.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockDatabaseConnectionMockRecorder) GetList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockDatabaseConnection)(nil).GetList), ctx)
}

// GetNextMatchId mocks base method.
func (m *MockDatabaseConnection) GetNextMatchId(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextMatchId", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextMatchId indicates an expected call of GetNextMatchId.
func (mr *MockDatabaseConnectionMockRecorder) GetNextMatchId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextMatchId", reflect.TypeOf((*MockDatabaseConnection)(nil).GetNextMatchId), ctx)
}

// ListenForQueueChange mocks base method.
func (m *MockDatabaseConnection) ListenForQueueChange(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForQueueChange", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenForQueueChange indicates an expected call of ListenForQueueChange.
func (mr *MockDatabaseConnectionMockRecorder) ListenForQueueChange(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForQueueChange", reflect.TypeOf((*MockDatabaseConnection)(nil).ListenForQueueChange), ctx)
}

// Open mocks base method.
func (m *MockDatabaseConnection) Open(ctx context.Context, config *internal.EnvConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockDatabaseConnectionMockRecorder) Open(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockDatabaseConnection)(nil).Open), ctx, config)
}

// SaveMatchResults mocks base method.
func (m *MockDatabaseConnection) SaveMatchResults(ctx context.Context, details string, matchID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMatchResults", ctx, details, matchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMatchResults indicates an expected call of SaveMatchResults.
func (mr *MockDatabaseConnectionMockRecorder) SaveMatchResults(ctx, details, matchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMatchResults", reflect.TypeOf((*MockDatabaseConnection)(nil).SaveMatchResults), ctx, details, matchID)
}

// MockMessage is a mock of Message interface.
type MockMessage struct {
	ctrl     *gomock.Controller
	recorder *MockMessageMockRecorder
	isgomock struct{}
}

// MockMessageMockRecorder is the mock recorder for MockMessage.
type MockMessageMockRecorder struct {
	mock *MockMessage
}

// NewMockMessage creates a new mock instance.
func NewMockMessage(ctrl *gomock.Controller) *MockMessage {
	mock := &MockMessage{ctrl: ctrl}
	mock.recorder = &MockMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessage) EXPECT() *MockMessageMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockMessage) Ack() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockMessageMockRecorder) Ack() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockMessage)(nil).Ack))
}

// Data mocks base method.
func (m *MockMessage) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockMessageMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockMessage)(nil).Data))
}

// MockMatchmaker is a mock of Matchmaker interface.
type MockMatchmaker struct {
	ctrl     *gomock.Controller
	recorder *MockMatchmakerMockRecorder
	isgomock struct{}
}

// MockMatchmakerMockRecorder is the mock recorder for MockMatchmaker.
type MockMatchmakerMockRecorder struct {
	mock *MockMatchmaker
}

// NewMockMatchmaker creates a new mock instance.
func NewMockMatchmaker(ctrl *gomock.Controller) *MockMatchmaker {
	mock := &MockMatchmaker{ctrl: ctrl}
	mock.recorder = &MockMatchmakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchmaker) EXPECT() *MockMatchmakerMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockMatchmaker) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockMatchmakerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockMatchmaker)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockMatchmaker) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockMatchmakerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMatchmaker)(nil).Start), ctx)
}
