// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	internal "server-manager/internal"

	gomock "go.uber.org/mock/gomock"
)

// MockDockerConnection is a mock of DockerConnection interface.
type MockDockerConnection struct {
	ctrl     *gomock.Controller
	recorder *MockDockerConnectionMockRecorder
	isgomock struct{}
}

// MockDockerConnectionMockRecorder is the mock recorder for MockDockerConnection.
type MockDockerConnectionMockRecorder struct {
	mock *MockDockerConnection
}

// NewMockDockerConnection creates a new mock instance.
func NewMockDockerConnection(ctrl *gomock.Controller) *MockDockerConnection {
	mock := &MockDockerConnection{ctrl: ctrl}
	mock.recorder = &MockDockerConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerConnection) EXPECT() *MockDockerConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDockerConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDockerConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDockerConnection)(nil).Close))
}

// GetGamePort mocks base method.
func (m *MockDockerConnection) GetGamePort(ctx context.Context, containerID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGamePort", ctx, containerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGamePort indicates an expected call of GetGamePort.
func (mr *MockDockerConnectionMockRecorder) GetGamePort(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGamePort", reflect.TypeOf((*MockDockerConnection)(nil).GetGamePort), ctx, containerID)
}

// Init mocks base method.
func (m *MockDockerConnection) Init(config *internal.EnvConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockDockerConnectionMockRecorder) Init(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockDockerConnection)(nil).Init), config)
}

// KillContainer mocks base method.
func (m *MockDockerConnection) KillContainer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KillContainer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// KillContainer indicates an expected call of KillContainer.
func (mr *MockDockerConnectionMockRecorder) KillContainer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillContainer", reflect.TypeOf((*MockDockerConnection)(nil).KillContainer), ctx, id)
}

// RestartContainer mocks base method.
func (m *MockDockerConnection) RestartContainer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartContainer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestartContainer indicates an expected call of RestartContainer.
func (mr *MockDockerConnectionMockRecorder) RestartContainer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartContainer", reflect.TypeOf((*MockDockerConnection)(nil).RestartContainer), ctx, id)
}

// SpawnContainer mocks base method.
func (m *MockDockerConnection) SpawnContainer(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnContainer", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpawnContainer indicates an expected call of SpawnContainer.
func (mr *MockDockerConnectionMockRecorder) SpawnContainer(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnContainer", reflect.TypeOf((*MockDockerConnection)(nil).SpawnContainer), ctx)
}

// MockBrokerConnection is a mock of BrokerConnection interface.
type MockBrokerConnection struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerConnectionMockRecorder
	isgomock struct{}
}

// MockBrokerConnectionMockRecorder is the mock recorder for MockBrokerConnection.
type MockBrokerConnectionMockRecorder struct {
	mock *MockBrokerConnection
}

// NewMockBrokerConnection creates a new mock instance.
func NewMockBrokerConnection(ctrl *gomock.Controller) *MockBrokerConnection {
	mock := &MockBrokerConnection{ctrl: ctrl}
	mock.recorder = &MockBrokerConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerConnection) EXPECT() *MockBrokerConnectionMockRecorder {
	return m.recorder
}

// AssignJob mocks base method.
func (m *MockBrokerConnection) AssignJob(ctx context.Context, workerID, config string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignJob", ctx, workerID, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignJob indicates an expected call of AssignJob.
func (mr *MockBrokerConnectionMockRecorder) AssignJob(ctx, workerID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignJob", reflect.TypeOf((*MockBrokerConnection)(nil).AssignJob), ctx, workerID, config)
}

// Close mocks base method.
func (m *MockBrokerConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrokerConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrokerConnection)(nil).Close))
}

// GetFinish mocks base method.
func (m *MockBrokerConnection) GetFinish(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFinish", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFinish indicates an expected call of GetFinish.
func (mr *MockBrokerConnectionMockRecorder) GetFinish(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFinish", reflect.TypeOf((*MockBrokerConnection)(nil).GetFinish), ctx)
}

// GetResult mocks base method.
func (m *MockBrokerConnection) GetResult(ctx context.Context) (internal.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult", ctx)
	ret0, _ := ret[0].(internal.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResult indicates an expected call of GetResult.
func (mr *MockBrokerConnectionMockRecorder) GetResult(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockBrokerConnection)(nil).GetResult), ctx)
}

// Open mocks base method.
func (m *MockBrokerConnection) Open(ctx context.Context, config *internal.EnvConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockBrokerConnectionMockRecorder) Open(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockBrokerConnection)(nil).Open), ctx, config)
}

// SendPing mocks base method.
func (m *MockBrokerConnection) SendPing() (internal.Responders, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPing")
	ret0, _ := ret[0].(internal.Responders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPing indicates an expected call of SendPing.
func (mr *MockBrokerConnectionMockRecorder) SendPing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPing", reflect.TypeOf((*MockBrokerConnection)(nil).SendPing))
}

// MockWorkerManager is a mock of WorkerManager interface.
type MockWorkerManager struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerManagerMockRecorder
	isgomock struct{}
}

// MockWorkerManagerMockRecorder is the mock recorder for MockWorkerManager.
type MockWorkerManagerMockRecorder struct {
	mock *MockWorkerManager
}

// NewMockWorkerManager creates a new mock instance.
func NewMockWorkerManager(ctrl *gomock.Controller) *MockWorkerManager {
	mock := &MockWorkerManager{ctrl: ctrl}
	mock.recorder = &MockWorkerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerManager) EXPECT() *MockWorkerManagerMockRecorder {
	return m.recorder
}

// AssignMatch mocks base method.
func (m *MockWorkerManager) AssignMatch(ctx context.Context, matchID int, config string) (internal.ServerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignMatch", ctx, matchID, config)
	ret0, _ := ret[0].(internal.ServerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignMatch indicates an expected call of AssignMatch.
func (mr *MockWorkerManagerMockRecorder) AssignMatch(ctx, matchID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignMatch", reflect.TypeOf((*MockWorkerManager)(nil).AssignMatch), ctx, matchID, config)
}

// Close mocks base method.
func (m *MockWorkerManager) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWorkerManagerMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkerManager)(nil).Close), ctx)
}

// HealthLoop mocks base method.
func (m *MockWorkerManager) HealthLoop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthLoop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthLoop indicates an expected call of HealthLoop.
func (mr *MockWorkerManagerMockRecorder) HealthLoop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthLoop", reflect.TypeOf((*MockWorkerManager)(nil).HealthLoop), ctx)
}

// Init mocks base method.
func (m *MockWorkerManager) Init(ctx context.Context, config *internal.EnvConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockWorkerManagerMockRecorder) Init(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockWorkerManager)(nil).Init), ctx, config)
}

// ResultLoop mocks base method.
func (m *MockWorkerManager) ResultLoop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResultLoop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResultLoop indicates an expected call of ResultLoop.
func (mr *MockWorkerManagerMockRecorder) ResultLoop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResultLoop", reflect.TypeOf((*MockWorkerManager)(nil).ResultLoop), ctx)
}

// SaveLoop mocks base method.
func (m *MockWorkerManager) SaveLoop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLoop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLoop indicates an expected call of SaveLoop.
func (mr *MockWorkerManagerMockRecorder) SaveLoop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLoop", reflect.TypeOf((*MockWorkerManager)(nil).SaveLoop), ctx)
}

// WaitForFreeWorker mocks base method.
func (m *MockWorkerManager) WaitForFreeWorker(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForFreeWorker", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForFreeWorker indicates an expected call of WaitForFreeWorker.
func (mr *MockWorkerManagerMockRecorder) WaitForFreeWorker(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForFreeWorker", reflect.TypeOf((*MockWorkerManager)(nil).WaitForFreeWorker), ctx)
}

// MockDatabaseConnection is a mock of DatabaseConnection interface.
type MockDatabaseConnection struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseConnectionMockRecorder
	isgomock struct{}
}

// MockDatabaseConnectionMockRecorder is the mock recorder for MockDatabaseConnection.
type MockDatabaseConnectionMockRecorder struct {
	mock *MockDatabaseConnection
}

// NewMockDatabaseConnection creates a new mock instance.
func NewMockDatabaseConnection(ctrl *gomock.Controller) *MockDatabaseConnection {
	mock := &MockDatabaseConnection{ctrl: ctrl}
	mock.recorder = &MockDatabaseConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseConnection) EXPECT() *MockDatabaseConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDatabaseConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabaseConnection)(nil).Close))
}

// Init mocks base method.
func (m *MockDatabaseConnection) Init(ctx context.Context, config *internal.EnvConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockDatabaseConnectionMockRecorder) Init(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockDatabaseConnection)(nil).Init), ctx, config)
}

// SaveMatchResult mocks base method.
func (m *MockDatabaseConnection) SaveMatchResult(ctx context.Context, result internal.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMatchResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMatchResult indicates an expected call of SaveMatchResult.
func (mr *MockDatabaseConnectionMockRecorder) SaveMatchResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMatchResult", reflect.TypeOf((*MockDatabaseConnection)(nil).SaveMatchResult), ctx, result)
}

// MockMessage is a mock of Message interface.
type MockMessage struct {
	ctrl     *gomock.Controller
	recorder *MockMessageMockRecorder
	isgomock struct{}
}

// MockMessageMockRecorder is the mock recorder for MockMessage.
type MockMessageMockRecorder struct {
	mock *MockMessage
}

// NewMockMessage creates a new mock instance.
func NewMockMessage(ctrl *gomock.Controller) *MockMessage {
	mock := &MockMessage{ctrl: ctrl}
	mock.recorder = &MockMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessage) EXPECT() *MockMessageMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockMessage) Ack() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockMessageMockRecorder) Ack() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockMessage)(nil).Ack))
}

// Data mocks base method.
func (m *MockMessage) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockMessageMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockMessage)(nil).Data))
}
