// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./interfaces.go -destination=../mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerConnection is a mock of BrokerConnection interface.
type MockBrokerConnection struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerConnectionMockRecorder
	isgomock struct{}
}

// MockBrokerConnectionMockRecorder is the mock recorder for MockBrokerConnection.
type MockBrokerConnectionMockRecorder struct {
	mock *MockBrokerConnection
}

// NewMockBrokerConnection creates a new mock instance.
func NewMockBrokerConnection(ctrl *gomock.Controller) *MockBrokerConnection {
	mock := &MockBrokerConnection{ctrl: ctrl}
	mock.recorder = &MockBrokerConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerConnection) EXPECT() *MockBrokerConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBrokerConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrokerConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrokerConnection)(nil).Close))
}

// GetMatchConfig mocks base method.
func (m *MockBrokerConnection) GetMatchConfig(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchConfig", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchConfig indicates an expected call of GetMatchConfig.
func (mr *MockBrokerConnectionMockRecorder) GetMatchConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchConfig", reflect.TypeOf((*MockBrokerConnection)(nil).GetMatchConfig), ctx)
}

// Open mocks base method.
func (m *MockBrokerConnection) Open(timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockBrokerConnectionMockRecorder) Open(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockBrokerConnection)(nil).Open), timeout)
}

// SendCancel mocks base method.
func (m *MockBrokerConnection) SendCancel() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCancel")
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCancel indicates an expected call of SendCancel.
func (mr *MockBrokerConnectionMockRecorder) SendCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCancel", reflect.TypeOf((*MockBrokerConnection)(nil).SendCancel))
}

// SendResult mocks base method.
func (m *MockBrokerConnection) SendResult(result []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResult", result)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendResult indicates an expected call of SendResult.
func (mr *MockBrokerConnectionMockRecorder) SendResult(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResult", reflect.TypeOf((*MockBrokerConnection)(nil).SendResult), result)
}

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// GetResult mocks base method.
func (m *MockServer) GetResult(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResult indicates an expected call of GetResult.
func (mr *MockServerMockRecorder) GetResult(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockServer)(nil).GetResult), ctx)
}

// Start mocks base method.
func (m *MockServer) Start(config string, command []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", config, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServerMockRecorder) Start(config, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServer)(nil).Start), config, command)
}

// Stop mocks base method.
func (m *MockServer) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockServerMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockServer)(nil).Stop), ctx)
}
