// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./interfaces.go -destination=./mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	internal "github.com/Matian37/multiplayer-asset/game-server/internal"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerConnection is a mock of BrokerConnection interface.
type MockBrokerConnection struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerConnectionMockRecorder
	isgomock struct{}
}

// MockBrokerConnectionMockRecorder is the mock recorder for MockBrokerConnection.
type MockBrokerConnectionMockRecorder struct {
	mock *MockBrokerConnection
}

// NewMockBrokerConnection creates a new mock instance.
func NewMockBrokerConnection(ctrl *gomock.Controller) *MockBrokerConnection {
	mock := &MockBrokerConnection{ctrl: ctrl}
	mock.recorder = &MockBrokerConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerConnection) EXPECT() *MockBrokerConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBrokerConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrokerConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrokerConnection)(nil).Close))
}

// GetMatchConfig mocks base method.
func (m *MockBrokerConnection) GetMatchConfig(ctx context.Context) (internal.MatchConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchConfig", ctx)
	ret0, _ := ret[0].(internal.MatchConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchConfig indicates an expected call of GetMatchConfig.
func (mr *MockBrokerConnectionMockRecorder) GetMatchConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchConfig", reflect.TypeOf((*MockBrokerConnection)(nil).GetMatchConfig), ctx)
}

// Open mocks base method.
func (m *MockBrokerConnection) Open(timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockBrokerConnectionMockRecorder) Open(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockBrokerConnection)(nil).Open), timeout)
}

// SendCancel mocks base method.
func (m *MockBrokerConnection) SendCancel(ctx context.Context, matchID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCancel", ctx, matchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCancel indicates an expected call of SendCancel.
func (mr *MockBrokerConnectionMockRecorder) SendCancel(ctx, matchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCancel", reflect.TypeOf((*MockBrokerConnection)(nil).SendCancel), ctx, matchID)
}

// SendResult mocks base method.
func (m *MockBrokerConnection) SendResult(ctx context.Context, matchID int, result []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResult", ctx, matchID, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendResult indicates an expected call of SendResult.
func (mr *MockBrokerConnectionMockRecorder) SendResult(ctx, matchID, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResult", reflect.TypeOf((*MockBrokerConnection)(nil).SendResult), ctx, matchID, result)
}

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// GetResult mocks base method.
func (m *MockExecutor) GetResult(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResult indicates an expected call of GetResult.
func (mr *MockExecutorMockRecorder) GetResult(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockExecutor)(nil).GetResult), ctx)
}

// Start mocks base method.
func (m *MockExecutor) Start(config string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockExecutorMockRecorder) Start(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockExecutor)(nil).Start), config)
}

// Stop mocks base method.
func (m *MockExecutor) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockExecutorMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockExecutor)(nil).Stop), ctx)
}
