// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/interfaces.go -destination=internal/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerConnection is a mock of BrokerConnection interface.
type MockBrokerConnection struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerConnectionMockRecorder
	isgomock struct{}
}

// MockBrokerConnectionMockRecorder is the mock recorder for MockBrokerConnection.
type MockBrokerConnectionMockRecorder struct {
	mock *MockBrokerConnection
}

// NewMockBrokerConnection creates a new mock instance.
func NewMockBrokerConnection(ctrl *gomock.Controller) *MockBrokerConnection {
	mock := &MockBrokerConnection{ctrl: ctrl}
	mock.recorder = &MockBrokerConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerConnection) EXPECT() *MockBrokerConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBrokerConnection) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrokerConnectionMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrokerConnection)(nil).Close), ctx)
}

// Connect mocks base method.
func (m *MockBrokerConnection) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockBrokerConnectionMockRecorder) Connect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockBrokerConnection)(nil).Connect), ctx)
}

// GetStartRequest mocks base method.
func (m *MockBrokerConnection) GetStartRequest(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStartRequest", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStartRequest indicates an expected call of GetStartRequest.
func (mr *MockBrokerConnectionMockRecorder) GetStartRequest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStartRequest", reflect.TypeOf((*MockBrokerConnection)(nil).GetStartRequest), ctx)
}

// SendMatchResult mocks base method.
func (m *MockBrokerConnection) SendMatchResult(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMatchResult", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMatchResult indicates an expected call of SendMatchResult.
func (mr *MockBrokerConnectionMockRecorder) SendMatchResult(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMatchResult", reflect.TypeOf((*MockBrokerConnection)(nil).SendMatchResult), ctx, payload)
}

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// GetResult mocks base method.
func (m *MockServer) GetResult(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResult indicates an expected call of GetResult.
func (mr *MockServerMockRecorder) GetResult(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockServer)(nil).GetResult), ctx)
}

// Start mocks base method.
func (m *MockServer) Start(config string, command []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", config, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServerMockRecorder) Start(config, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServer)(nil).Start), config, command)
}

// Stop mocks base method.
func (m *MockServer) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockServerMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockServer)(nil).Stop), ctx)
}
