name: game-server e2e

on:
  pull_request:
    branches: ["main"]
    paths:
      - "game-server/**"

defaults:
  run:
    working-directory: ./game-server/host/

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
          cache: true
          cache-dependency-path: "game-server/host/go.sum"

      - name: Run E2E Tests
        run: go test -v -tags=e2e -run="^TestE2E" --timeout 3m ./...
